// Mock data for the entire app

export const ONBOARDING_SLIDES = [
  {
    id: 1,
    title: 'Tired of expensive\nsolo rides?',
    subtitle: 'Public transport wasting too much of your time and energy?',
    backgroundColor: '#2C3E6B',
    image: require('../../assets/onboarding_bus.png'),
  },
  {
    id: 2,
    title: 'Share rides,\nsave money',
    subtitle: 'Need a smarter way for your daily commute and weekends?',
    backgroundColor: '#1B7A3D',
    image: require('../../assets/onboarding_carpool.png'),
  },
  {
    id: 3,
    title: 'Sign up and start\nsaving today',
    subtitle: 'Join thousands of commuters saving 40-50% on every ride',
    backgroundColor: '#1E6B8A',
    image: require('../../assets/onboarding_signup.png'),
  },
];

export const VEHICLE_TYPES = [
  { id: 'all', label: 'All' },
  { id: 'economy', label: 'Economy' },
  { id: 'eco', label: 'ECO 🌿' },
  { id: 'comfort', label: 'Comfort' },
  { id: 'premium', label: 'Premium' },
];

export const MOCK_VEHICLES = [
  {
    id: 1,
    name: 'Maruti Suzuki Swift',
    type: 'Economy',
    category: 'economy',
    distance: '300 m',
    fare: '₹280',
    farePerKm: '₹8/km',
    eta: '3 min',
    rating: 4.8,
    seats: 3,
    image: null,
    driver: {
      name: 'Rajesh K.',
      rating: 4.9,
      trips: 1250,
    },
  },
  {
    id: 2,
    name: 'Hyundai i20',
    type: 'Comfort',
    category: 'comfort',
    distance: '500 m',
    fare: '₹320',
    farePerKm: '₹10/km',
    eta: '5 min',
    rating: 4.7,
    seats: 3,
    image: null,
    driver: {
      name: 'Amit S.',
      rating: 4.8,
      trips: 890,
    },
  },
  {
    id: 3,
    name: 'Toyota Innova',
    type: 'Premium',
    category: 'premium',
    distance: '800 m',
    fare: '₹450',
    farePerKm: '₹14/km',
    eta: '7 min',
    rating: 4.9,
    seats: 6,
    image: null,
    driver: {
      name: 'Vikram P.',
      rating: 4.9,
      trips: 2100,
    },
  },
  {
    id: 4,
    name: 'Tata Nexon EV',
    type: 'ECO 🌿',
    category: 'eco',
    distance: '600 m',
    fare: '₹300',
    farePerKm: '₹9/km',
    eta: '4 min',
    rating: 4.6,
    seats: 3,
    image: null,
    driver: {
      name: 'Priya M.',
      rating: 4.7,
      trips: 560,
    },
  },
];

export const MOCK_MATCHES = [
  {
    id: 1,
    passenger: {
      name: 'Arun K.',
      rating: 4.8,
      verified: true,
      avatar: null,
    },
    pickup: 'Rajiv Chowk Metro',
    dropoff: 'Noida Sector 15',
    overlap: 78,
    savings: '₹180',
    sharedFare: '₹320',
    soloFare: '₹500',
    eta: '3 min',
    detour: '+5 min',
  },
  {
    id: 2,
    passenger: {
      name: 'Sneha R.',
      rating: 4.9,
      verified: true,
      avatar: null,
    },
    pickup: 'India Gate',
    dropoff: 'Akshardham',
    overlap: 85,
    savings: '₹200',
    sharedFare: '₹280',
    soloFare: '₹480',
    eta: '5 min',
    detour: '+3 min',
  },
];

export const MOCK_TRIPS = [
  {
    id: 1,
    date: '15 Mar 2026',
    time: '9:30 AM',
    pickup: 'Connaught Place',
    dropoff: 'Akshardham',
    fare: '₹320',
    savings: '₹180',
    type: 'Shared',
    rating: 5,
    driver: 'Rajesh K.',
    distance: '15 km',
    duration: '35 min',
  },
  {
    id: 2,
    date: '14 Mar 2026',
    time: '6:45 PM',
    pickup: 'Gurgaon Sector 44',
    dropoff: 'Rajiv Chowk',
    fare: '₹410',
    savings: '₹140',
    type: 'Shared',
    rating: 4,
    driver: 'Amit S.',
    distance: '22 km',
    duration: '50 min',
  },
  {
    id: 3,
    date: '13 Mar 2026',
    time: '8:15 AM',
    pickup: 'Noida Sector 62',
    dropoff: 'Connaught Place',
    fare: '₹500',
    savings: null,
    type: 'Solo',
    rating: 5,
    driver: 'Vikram P.',
    distance: '18 km',
    duration: '40 min',
  },
];

export const MOCK_DRIVER_STATS = {
  todayEarnings: '₹2,840',
  weekEarnings: '₹18,250',
  monthEarnings: '₹72,500',
  todayRides: 8,
  rating: 4.9,
  streak: 4,
  streakTarget: 5,
  completionRate: '96%',
  acceptanceRate: '92%',
  returnTripUsedToday: false,
  isOnline: true,
};

export const MOCK_RIDE_REQUESTS = [
  {
    id: 1,
    pickup: 'Rajiv Chowk',
    dropoff: 'Noida Sector 15',
    distance: '18 km',
    estimatedEarnings: '₹380',
    isShared: true,
    passengers: 2,
    eta: '3 min to pickup',
  },
  {
    id: 2,
    pickup: 'India Gate',
    dropoff: 'Gurgaon Sector 29',
    distance: '25 km',
    estimatedEarnings: '₹520',
    isShared: false,
    passengers: 1,
    eta: '5 min to pickup',
  },
];

export const USER_PROFILE = {
  name: 'Shubham Gangwar',
  phone: '+91 98765 43210',
  email: 'shubham@rideshare.in',
  rating: 4.8,
  totalRides: 47,
  totalSavings: '₹4,280',
  subscription: 'Premium',
  verified: true,
  savedPlaces: [
    { id: 1, label: 'Home', address: 'Sector 62, Noida' },
    { id: 2, label: 'Office', address: 'Connaught Place, New Delhi' },
    { id: 3, label: 'Gym', address: 'Sector 18, Noida' },
  ],
  paymentMethods: [
    { id: 1, type: 'UPI', label: 'GPay - shubham@oksbi', primary: true },
    { id: 2, type: 'Card', label: 'HDFC •••• 4589' },
    { id: 3, type: 'Wallet', label: 'Paytm Wallet' },
  ],
  emergencyContacts: [
    { id: 1, name: 'Mom', phone: '+91 98765 12345' },
    { id: 2, name: 'Dad', phone: '+91 98765 67890' },
  ],
};
